"""모든 결정의 단일 원본. API 명세(10장)와 해설집이 같은 데이터를 씀.

필드: id, cat, title, situation, plan, problem, choice, why, front, test, status
status: 확정 / 전원 알림 / 팀 확인 필요
"""

CATS = {
    "D": ("검증에서 발견한 문제", "명세대로 코드를 돌려 보고 실제 데이터·모델로 시험해서 찾은 것. 기획서를 그대로 따르면 서비스에서 문제가 생기는 곳이라 고쳤어요."),
    "A": ("API 약속 정리", "기획서가 정하지 않은 HTTP 코드·필드 이름 같은 약속. 다른 에이전트가 만든 노션 초안과 비교해서 더 나은 쪽을 골랐어요."),
    "R": ("세부 규칙", "기획서·Figma가 애매하게 남긴 부분을 권장안으로 정한 것."),
}

DECISIONS = [
    # ─── 검증에서 발견 ───────────────────────────────────
    dict(id="D01", cat="D", title="시간 표현 표를 넓힘 (\"아침에\", \"이틀 전\", \"지난밤\")",
         situation="보호자가 \"아침에 여기가 어디냐고 물으심\", \"이틀 전에 넘어지심\"처럼 흔하게 씀.",
         plan="기획안 4-5 변환표는 11개 표현(오늘·아까·낮에·저녁에·어제·어젯밤·어제 저녁·그저께·그제·새벽·N일 전)만 있고, 나머지는 모두 '날짜 알 수 없음 → 통계에서 뺌'.",
         problem="팀 학습 데이터의 시간 표현은 딱 14종뿐이었음. 보호자가 흔히 쓰는 표현 30개를 날짜 규칙에 넣어 보니 \"아침에\", \"밤에\", \"이틀 전\", \"지난밤\" 등 절반 가까이가 '날짜 알 수 없음'이 되어 통계에서 사라짐. 날짜가 분명한데도 빠지는 것.",
         choice="기획안의 11개는 그대로 두고 보탬: 지난밤·간밤(−1일), 엊그제(−2일), 하루·이틀·사흘·나흘·닷새 전(−N일), 아침에·오전에·점심때·오후에·밤에·방금(작성일). \"밤마다\", \"매일\", \"자주\", \"지난달\"처럼 되풀이·기간 표현은 '알 수 없음'에 보탬.",
         why="기획안이 이미 \"저녁에 = 작성일\"로 정한 규칙을 다른 때 표현에도 똑같이 적용한 것이라 기획 의도와 같음. 틀리면 카드에서 고칠 수 있으니 빠지는 것보다 나음.",
         front="바꿀 것 없음. 결과 카드의 발생일 칸을 눈에 띄게 두기만 하면 됨.",
         test="데이터 점검(팀 데이터 2,477건) · 보호자 말투 표현 30개 · 날짜 단위 테스트",
         status="전원 알림 (settings.yaml date_expressions가 바뀜)"),
    dict(id="D02", cat="D", title="기준 구간 기록이 14일 미만이면 '비교 불가'",
         situation="앱을 처음 깐 보호자가 지난 진료일 두 개를 등록하고, 그때부터 기록을 시작함 → 기준 구간 기록이 0~2일.",
         plan="기획안 3-4는 '이번 구간 기록일 14일 미만 → 기록 부족'만 있고 기준 구간 쪽 규칙은 없음.",
         problem="기준 구간 기록이 0일이면 0으로 나눠서 서버가 멈춤(요약지 오류). 1~2일이면 비율이 0% 아니면 100%라, 하루치 기록만으로 '새로 나타남'이 붙음.",
         choice="기준 구간 기록일이 14일 미만이면 그 요약지의 모든 유형을 not_comparable(비교 불가)로. 응답의 baseline에 recorded_days·total_days를 넣음.",
         why="이번 구간에 쓰는 14일 기준을 비교 대상에도 똑같이 쓰는 것. 새 판단이 아니라 기존 기준을 대칭으로 맞춘 것.",
         front="비교 불가 설명을 두 가지로: baseline이 null이면 \"첫 진료라 비교할 기간이 없어요\", baseline.recorded_days < 14면 \"기준 구간 기록이 N일뿐이라 비교하지 않았어요\".",
         test="통계 단위 테스트에서 0으로 나누기 오류 재현 → 규칙 적용 후 통과",
         status="전원 알림 (settings.yaml에 min_baseline_recorded_days: 14 추가)"),
    dict(id="D03", cat="D", title="기준일 당일의 진료는 '오늘 갈 진료'로 봄",
         situation="진료 당일 아침, 진료일을 먼저 등록하고 요약지를 열어 인쇄함.",
         plan="기획안 3-4: 이번 구간 = 직전 진료일 ~ 요약지 만드는 날.",
         problem="오늘 등록한 진료가 '직전 진료'가 되어 이번 구간이 하루짜리가 됨 → 모든 유형 '기록 부족', 요약지가 텅 빔. 등록 순서 하나로 데모가 망가짐.",
         choice="기준일(as_of)보다 앞선 진료일만 '지난 진료'로 씀. 기준일 당일의 진료는 오늘 갈 진료로 보고, 다음 날부터 새 구간이 시작됨.",
         why="요약지는 오늘 가져갈 문서라 오늘 진료는 구간 끝이어야 함. 보호자가 등록 순서를 신경 쓸 필요가 없어짐.",
         front="일정 화면: 오늘 날짜 진료일에는 \"오늘 진료\" 뱃지. \"지난 진료 · 이번 구간 시작\" 뱃지는 오늘보다 앞선 진료일 중 최신에.",
         test="구간 단위 테스트(당일 등록·다음 날)",
         status="확정"),
    dict(id="D04", cat="D", title="% 반올림을 백엔드·프론트가 같은 숫자로",
         situation="요약지의 AI 요약 문장(서버가 만듦)과 영역별 표(프론트가 그림)에 같은 비율이 나옴.",
         plan="기획안 8-5 성공 기준: \"요약 문장의 숫자 = 표의 숫자\". 반올림 방법은 없음.",
         problem="서버는 파이썬, 표는 자바스크립트라 반올림이 다름(파이썬 round(12.5)=12, JS=13). 응답에는 소수 넷째 자리로 보내므로 두 번 반올림도 생김. 기록일 200일까지 모든 경우를 돌려 보니 39가지 경우에서 1%p 어긋남(예: 101일 중 51일 → 문장 50%, 표 51%). 모두 기록일 100일 넘는 경우라 91일짜리 데모 기준 구간 근처에서 생길 수 있음.",
         choice="서버는 응답에 넣는 값(소수 넷째 자리)으로 %를 만들고 int(x × 100 + 0.5)로 반올림. 프론트는 Math.round(rate × 100).",
         why="같은 숫자에서 같은 방식으로 반올림하면 항상 같음. 20,000가지 넘는 경우 모두 일치 확인.",
         front="%는 Math.round(rate * 100)만 씀. toFixed()나 Intl.NumberFormat은 반올림 방식이 달라서 쓰지 않음.",
         test="반올림 전수 테스트(기록일 1~200일, 20,100가지)",
         status="확정"),
    dict(id="D05", cat="D", title="요약지 화면 주소를 /report로",
         situation="요약지 화면에서 새로고침하거나 주소를 즐겨찾기함.",
         plan="API 경로 GET /summary는 기획안 5-5에서 동결. Figma는 요약지 화면 주소도 /summary.",
         problem="화면 주소와 API 주소가 같아서 새로고침하면 화면 대신 JSON 글자가 나옴. 그리고 /record 등 다른 화면도 새로고침하면 404.",
         choice="화면 주소만 /report로 바꿈(메뉴 이름은 그대로 '요약지'). 서버는 모르는 주소를 브라우저가 열면 화면 파일(index.html)을 돌려줌.",
         why="동결된 API 경로를 바꾸면 여러 곳을 고쳐야 하지만, 화면 주소는 프론트 라우터 한 줄.",
         front="React 라우터의 요약지 경로를 /report로.",
         test="서버 구조 시험: 고치기 전 /record 새로고침 404·/summary JSON → 고친 뒤 화면 정상",
         status="확정 (프론트 알림)"),
    dict(id="D06", cat="D", title="AI 핵심 요약 검사를 2가지 더함",
         situation="요약지 첫 장의 AI 핵심 요약(베이스 모델이 쓰고 코드가 검사).",
         plan="기획안 4-8: 베이스 모델이 작성 → 코드가 4가지 검사(숫자·금지 표현·원인 해석·누락) → 떨어지면 문장 틀.",
         problem="검사 코드를 짜서 시험해 보니, 4가지 검사로는 \"배회가 증가됨\"처럼 숫자 없는 빈 문장과, 증가한 유형을 \"새로 나타남\"처럼 쓴 뒤바뀐 사실을 걸러내지 못함.",
         choice="검사 2개를 보탬: ① 표시 붙은 유형 문장에 그 유형의 이번 구간 %(새로 나타남은 처음 기록된 날), 낙상 문장에 날짜가 있어야 함 ② 증가 유형을 '처음 기록'처럼, 새로 나타남 유형을 '증가'처럼 쓰면 탈락.",
         why="의사가 보는 문서라, 틀린 문장보다 문장 틀이 나음. 기획안이 정한 '떨어지면 문장 틀' 안전망 그대로. 모델이 무엇이든 똑같이 적용되는 코드 쪽 검사.",
         front="바꿀 것 없음(summary_source로 라벨이 이미 갈림).",
         test="검사 코드 시험: 사람이 쓴 정답 요약은 통과, 빈 문장·뒤바뀐 사실은 탈락",
         status="확정"),
    dict(id="D07", cat="D", title="모델을 부르는 서버 함수는 async를 쓰지 않음",
         situation="백엔드를 FastAPI로 만듦.",
         plan="개발 가이드 3-4는 동기식 ollama.Client로 모델을 부름.",
         problem="이 호출을 async def 함수 안에 쓰면 AI가 일하는 동안 서버 전체가 멈춤. 헤더의 모델 상태 확인(/health)이 2.83초 멈춤(보통 0.01초). 실제로는 최대 4분.",
         choice="모델을 부르는 API 함수는 보통 def로 씀.",
         why="FastAPI는 보통 def를 별도 일꾼(스레드)에서 돌려서 다른 요청이 계속 처리됨.",
         front="없음 (백엔드 내부).",
         test="서버 구조 시험(async def 2.83초 vs def 0.01초)",
         status="확정"),
    dict(id="D08", cat="D", title="응급 키워드 오탐은 기획안대로 둠",
         situation="메모에 응급 키워드가 있으면 119 안내를 띄움.",
         plan="기획안 7-3: 부분 일치로 찾고, 불필요한 안내(오탐)가 생겨도 필요한 안내를 놓치는 것보다 낫다고 판단.",
         problem="팀 데이터 2,477건 중 4건에 안내가 뜨는데 3건이 오탐(\"리모컨을 못 찾으시자\", \"고양이가 … 없어졌다 하시고\"). 실사용에서는 \"지갑이 없어졌다\"(흔한 망상 표현)에도 뜰 것.",
         choice="바꾸지 않음.",
         why="기획안이 이미 알고 받아들인 위험이고, 안전 쪽으로 기우는 것이 맞음. 이런 건 '정말 중요한 이슈'가 아니라 기획안을 따름.",
         front="안내 아래 작은 글씨 \"안내가 뜨지 않았다고 괜찮은 상황이라는 뜻은 아니에요.\"를 항상 표시. 안내 문구는 한 글자도 바꾸지 않음.",
         test="팀 데이터 전체 검색",
         status="확정 (기획안 그대로)"),
    dict(id="D09", cat="D", title="동결 파일이 레포에 없음",
         situation="9/29 기준 세 레포 상태.",
         plan="개발 가이드 0-3: event_schema.json · labels.json · schemas.py · settings.yaml을 9/27에 동결해서 필요한 레포에 복사.",
         problem="itda-ai에는 labels.json·system_prompt.txt만 있음. itda-backend는 비어 있음.",
         choice="이 명세 10장에 settings.yaml 전체 내용(기획안 5-7 + v2.1 추가 키)과 event_schema.json을 실음. 모델 이름·요약 모델 두 값은 모델 테스트가 끝나면 AI팀이 채움.",
         why="동결 파일이 없으면 사람마다 다른 값을 씀. 모델 관련 값은 설정 파일에만 두고 코드에 박지 않아서, 나중에 바꿔도 코드는 그대로.",
         front="없음 (프론트는 labels.json만 씀).",
         test="레포 파일 목록 확인",
         status="팀 확인 필요 (모델 값은 AI팀 테스트 후)"),
    dict(id="A01", cat="A", title="AI가 실패해도 HTTP는 200", situation="AI 정리·요약이 실패함.",
         plan="\"AI 실패는 오류가 아님\"(status=failed, 문장 틀). HTTP 코드는 안 정함.",
         problem="v2.0은 POST /memos가 201이었는데, 실패한 retry는 200이라 일관되지 않았음.",
         choice="POST /memos · retry · GET /summary는 AI가 실패해도 모두 200. 결과는 status / summary_source로 구분.",
         why="프론트는 HTTP 코드가 아니라 status만 보고 화면을 바꾸면 됨.", front="res.ok면 status로 분기.", test="-", status="확정"),
    dict(id="A02", cat="A", title="순서가 안 맞는 요청은 409", situation="진료일 없이 요약지를 열거나, 이미 저장한 메모를 다시 승인함.",
         plan="없음.", problem="v2.0은 진료일 없음을 422로 했는데 입력이 틀린 게 아니라 상태가 안 맞는 것.",
         choice="no_visit·memo_already_confirmed·memo_failed·memo_not_confirmed·visit_exists는 409. 입력 형식 오류만 422. as_of_before_visit는 D03으로 필요 없어져 없앰.",
         why="409 = 지금 상태로는 못 함, 422 = 보낸 값이 틀림. 프론트가 문구를 고르기 쉬움.", front="7장 오류표대로 문구.", test="-", status="확정"),
    dict(id="A03", cat="A", title="오류 코드는 소문자, 무엇이 없는지까지", situation="오류 응답 {\"detail\": \"…\"}.",
         plan="없음.", problem="v2.0은 NOT_FOUND 하나로 진료일·약·질문을 모두 표현.",
         choice="memo_not_found, visit_not_found, medication_not_found, question_not_found처럼 소문자 + 대상.",
         why="로그와 프론트 문구 표를 맞추기 쉬움.", front="ApiErrorCode 타입 그대로.", test="-", status="확정"),
    dict(id="A04", cat="A", title="같은 뜻은 같은 이름", situation="응답 필드 이름.",
         plan="기획안 5-5 동결 필드.", problem="v2.0은 메모 목록에서 id, POST /memos에서 memo_id. /health는 model, 설정은 model_name.",
         choice="메모 번호는 어디서나 memo_id, /health는 model_name.", why="프론트가 헷갈리지 않음.", front="MemoItem.memo_id, Health.model_name.", test="-", status="확정"),
    dict(id="A05", cat="A", title="승인 응답은 개수만", situation="[모두 맞아요] 성공.",
         plan="없음.", problem="v2.0은 저장된 사건 목록 전체를 돌려줬는데 화면은 바로 입력 상태로 돌아가 쓰지 않음.",
         choice="{memo_id, status: \"confirmed\", event_count}.", why="쓰지 않는 데이터를 만들지 않음.", front="ConfirmResponse 타입.", test="-", status="확정"),
    dict(id="A06", cat="A", title="데모 불러오기는 기준일(as_of)을 함께 줌", situation="발표일(9/30)에 데모 요약지를 엶.",
         plan="데모 기간 5/21~9/26(개발 가이드 2-9).",
         problem="오늘(9/30) 기준으로 요약지를 부르면 기록 없는 4일이 더해져 커버리지·비율이 달라짐.",
         choice="POST /demo/load 응답에 as_of: \"2026-09-26\".", why="데모 숫자가 발표 자료와 같게 유지됨.",
         front="데모를 불러오면 as_of를 저장해 두고, 요약지·경과를 그 날짜로 부름. 새 메모를 저장하면 해제.", test="-", status="확정 (프론트 알림)"),
    dict(id="A07", cat="A", title="가명이 없으면 빈칸", situation="가명 입력 화면이 없음.",
         plan="patient.alias(가명). 입력 경로 없음.", problem="v2.0은 \"환자\"라고 찍었는데 인쇄본에서 어색함.",
         choice="patient_alias = \"\" → 인쇄본에 \"환자: ________\" 빈 밑줄.", why="보호자가 손으로 적을 수 있음.",
         front="\"\"이면 빈 밑줄.", test="-", status="확정 (프론트 알림)"),
    dict(id="A08", cat="A", title="영역별 표 정렬은 프론트가", situation="요약지 표 순서.",
         plan="표시 붙은 유형을 위에(기획안 3-5). 첫 장이 넘치면 0% 유형부터 뒷장으로.",
         problem="v2.0은 서버가 정렬했는데, 어떤 행을 뒷장으로 넘길지는 프론트만 앎(인쇄 공간).",
         choice="서버는 labels.json 순서로 12개를 줌. 프론트가 increase·new를 위로 올림.", why="정렬과 넘김을 한 곳에서.",
         front="rows를 정렬: mark가 increase·new인 행 먼저, 나머지는 받은 순서.", test="-", status="확정 (프론트 알림)"),
    dict(id="A09", cat="A", title="직접 추가한 사건은 근거 구절이 비어도 됨", situation="보호자가 [빠진 사건 추가]로 넣음.",
         plan="evidence = 원문 구절 그대로.", problem="직접 넣은 사건은 원문에 해당 구절이 없을 수 있음.",
         choice="source가 manual이면 evidence = \"\" 허용.", why="억지로 문장을 쓰게 하지 않음.", front="evidence가 \"\"이면 강조를 건너뜀.", test="-", status="확정"),
    dict(id="A10", cat="A", title="값 검사는 API와 DB 두 군데", situation="잘못된 유형 코드 같은 값.",
         plan="Pydantic 검사(가이드 3-4).", problem="데모 불러오기는 API를 거치지 않고 DB에 바로 넣어서 Pydantic을 안 거침.",
         choice="API는 Pydantic Literal, DB는 CHECK 제약. 인덱스는 선택(수천 행 규모).", why="데모 파일의 오타도 막음.", front="없음.", test="DDL 실행 시험", status="확정"),

    # ─── 세부 규칙 ─────────────────────────────────────
    dict(id="R01", cat="R", title="요약지 표 행에 3개 필드 추가", situation="Figma 경과 카드 \"기록일 34일 중 13일\", \"9월 7일 처음 기록 · 총 3일\".",
         plan="rows는 type·baseline_rate·current_rate·weekly_count·mark로 동결.", problem="이 값들이 없어서 카드를 만들 수 없음(비율로 역산하면 오차, 첫 날짜는 불가).",
         choice="current_days · baseline_days · first_date 추가. 기존 필드는 그대로.", why="기존 코드가 안 깨지는 확장.",
         front="카드에 그대로 씀.", test="-", status="전원 알림 (동결 모양 확장)"),
    dict(id="R02", cat="R", title="메모 1개 다시 열기 GET /memos/{id} (P1)", situation="최근 기록에서 '확인 대기' 메모를 누름.",
         plan="기획안 5-5 목록에 없음.", problem="확인 전 결과는 memos.model_output에만 있어서 목록 API로는 카드를 다시 못 만듦.",
         choice="GET /memos/{id} 추가. 모델을 다시 부르지 않고 저장된 결과로 카드를 만듦.", why="Figma 동작에 필요.", front="확인 대기·실패 항목 클릭 시 호출.", test="-", status="확정"),
    dict(id="R03", cat="R", title="빠진 사건 추가는 두 길", situation="모델이 놓친 증상을 보호자가 넣음(F-12, P1).",
         plan="POST /events. 모양은 안 정함.", problem="확인 중인 메모와 이미 저장된 메모는 흐름이 다름.",
         choice="확인 중: 화면에서 manual 카드를 더해 승인 때 함께 보냄. 이미 저장됨: POST /events.", why="확인 중에 서버를 한 번 더 부를 필요가 없음.", front="두 경우를 구분.", test="-", status="확정"),
    dict(id="R04", cat="R", title="근거 원문은 발생일 기준 + 유형 필터", situation="요약 문장을 누르면 근거 메모를 보여 줌(F-14).",
         plan="GET /memos?dates=.", problem="문장의 날짜는 발생일인데 메모는 작성일로 저장됨. 한 메모에 증상이 여러 개.",
         choice="dates = 발생일, types = 그 문장의 유형. events에는 조건에 맞는 사건만.", why="9/25 일을 9/26에 쓴 메모도 찾고, 강조할 구절을 고를 수 있음.", front="\"9월 25일 발생 · 9월 26일 작성\".", test="-", status="확정"),
    dict(id="R05", cat="R", title="요약지 약·낙상의 범위", situation="요약지 뒷장 약 변경·낙상 목록.",
         plan="\"약·낙상 목록(날짜순)\"만 있음.", problem="어느 기간인지 없음. Figma 뒷장에 기준 구간(6/15)의 약도 보임.",
         choice="약: 기준 구간 시작 ~ 기준일. 낙상: 이번 구간.", why="약은 비교 맥락이 필요하고, 낙상은 이번 진료에 알릴 일.", front="없음.", test="-", status="확정"),
    dict(id="R06", cat="R", title="주는 월요일 시작", situation="주간 추이 그래프.", plan="없음.", problem="-", choice="월요일 시작, 기준 구간 시작 주 ~ 기준일 주.", why="ISO 주 기준.", front="week_start를 x축 라벨로.", test="-", status="확정"),
    dict(id="R07", cat="R", title="진료일은 오늘까지, 중복 불가", situation="진료일 등록.", plan="없음.",
         problem="미래 날짜면 구간이 거꾸로, 중복이면 기준 구간이 0일.", choice="오늘 이후 422 visit_date_in_future, 중복 409 visit_exists.", why="구간 계산 보호.", front="날짜 입력에 max=오늘.", test="-", status="확정"),
    dict(id="R08", cat="R", title="/health에 allow_lan", situation="휴대폰 접속 경고 띠.", plan="기획안 7-4 경고 문구.",
         problem="프론트가 서버의 설정을 알 방법이 없음.", choice="/health 응답에 allow_lan.", why="Figma 명세 카드 0의 제안.", front="true면 헤더 아래 띠.", test="-", status="확정"),
    dict(id="R09", cat="R", title="요약지에 들어가는 질문", situation="질문 메모 중 무엇을 요약지에 넣나.",
         plan="\"직전 진료일 이후 것만\".", problem="진료 당일 쓴 질문은? '직전'이 지난 진료인지 다음 진료인지 팀 대화에서 헷갈림.",
         choice="created_at ≥ 이번 구간 시작일(= 지난 진료일, 당일 포함). GET /questions에 in_summary로 알려 줌.", why="진료 당일 대기실에서 쓴 질문도 다음 요약지에.",
         front="in_summary로 뱃지.", test="-", status="확정"),
    dict(id="R10", cat="R", title="정리 실패 메모는 승인 불가", situation="정리 실패 화면에서 승인 시도.", plan="없음.",
         problem="빈 목록으로 승인되면 관찰 없는 날이 기록일이 되어 비율이 낮아짐.", choice="409 memo_failed. 다시 시도 먼저.", why="통계 보호.", front="실패 상태에서는 승인 버튼 없음.", test="-", status="확정"),
    dict(id="R11", cat="R", title="이미 저장한 메모는 다시 승인 불가", situation="같은 메모를 두 번 승인.", plan="없음.",
         problem="두 번 저장되면 횟수가 2배.", choice="409 memo_already_confirmed. (v2.0의 '교체'에서 바꿈)", why="수정 기능이 범위 밖이라 교체가 필요 없음.", front="승인 성공 뒤 입력 상태로.", test="-", status="확정"),
    dict(id="R12", cat="R", title="메모 삭제 없음", situation="메모를 지우고 싶음.", plan="기획안·Figma에 없음.", problem="-",
         choice="만들지 않음(데모 불러오기의 전체 비우기만).", why="범위 밖.", front="없음.", test="-", status="확정"),
    dict(id="R13", cat="R", title="질문 작성일은 앱이 로컬 날짜로", situation="질문 저장.", plan="created_at DATE.",
         problem="SQLite 기본값 CURRENT_DATE는 UTC라 한국 새벽 0~9시에 전날로 들어감.", choice="앱이 dt.date.today()로 넣음.", why="날짜 밀림 방지.", front="없음.", test="-", status="확정"),
    dict(id="R14", cat="R", title="오래 걸리는 요청의 대기 시간", situation="AI 처리 대기.", plan="모델 120초·요약 180초, 각 재시도 1회.",
         problem="프론트가 짧게 끊으면 성공한 요청도 실패로 보임.", choice="메모 정리 250초, 요약지 370초 이상 기다림.", why="최악의 경우보다 길게.", front="fetch에 짧은 타임아웃을 걸지 않음. 로딩 중 버튼 막기.", test="-", status="확정"),
    dict(id="R15", cat="R", title="디자인_수정목록", situation="개발 가이드 4-3이 가리키는 문서.", plan="\"디자인_수정목록을 따름\".",
         problem="파일이 없음.", choice="받는 대로 반영.", why="-", front="-", test="-", status="팀 확인 필요 (기획)"),
    dict(id="R16", cat="R", title="메모는 최대 1,000자",
         situation="보호자가 며칠 치를 한 번에 몰아서 길게 씀.",
         plan="기획안에 길이 제한 없음. Figma 명세 카드(결정 필요 4번)가 1,000자를 제안.",
         problem="제한이 없으면 아주 긴 글이 AI에 한 번에 들어가 처리 시간과 품질을 예측할 수 없음.",
         choice="1~1,000자. 넘으면 422. 값은 settings.yaml의 memo_max_chars로 두어 모델 테스트 결과에 따라 바꿀 수 있게.",
         why="Figma 카드의 제안을 그대로 받음. 설정값이라 코드를 고치지 않고 조정 가능.",
         front="입력칸 아래 \"123 / 1,000\" 글자 수 표시, 1,000자 넘으면 버튼 비활성.",
         test="-",
         status="확정 (프론트 알림)"),
]


# 기획서와의 관계: 변경 = 기획서·Figma·동결 파일에 적힌 것을 바꿈 / 보완 = 기획서가 정하지 않은 곳을 채움 / 유지 = 문제를 봤지만 기획서대로 둠
KIND = {"D01": "변경", "D03": "변경", "D05": "변경", "R01": "변경", "D08": "유지"}
for _d in DECISIONS:
    _d["kind"] = KIND.get(_d["id"], "보완")
